src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <formula>CASE( Renewal_Anniversary_Month__c , 
&apos;JAN&apos;,DATE( YEAR( TODAY() ) ,1,1), 
&apos;FEB&apos;,DATE( YEAR( TODAY() ) ,2,1), 
&apos;MAR&apos;,DATE( YEAR( TODAY() ) ,3,1), 
&apos;APR&apos;,DATE( YEAR( TODAY() ) ,4,1), 
&apos;MAY&apos;,DATE( YEAR( TODAY() ) ,5,1), 
&apos;JUN&apos;,DATE( YEAR( TODAY() ) ,6,1), 
&apos;JUL&apos;,DATE( YEAR( TODAY() ) ,7,1), 
&apos;AUG&apos;,DATE( YEAR( TODAY() ) ,8,1), 
&apos;SEP&apos;,DATE( YEAR( TODAY() ) ,9,1), 
&apos;OCT&apos;,DATE( YEAR( TODAY() ) ,10,1), 
&apos;NOV&apos;,DATE( YEAR( TODAY() ) ,11,1), 
&apos;DEC&apos;,DATE( YEAR( TODAY() ) ,12,1), 
NULL)</formula>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

src/objects/Benfit_Request_Form__c.object
<CustomObject>
    <description>New object for AIA - This object stores the information that is needed for a quote</description>
    <fields>
        <fullName>Benefit_Effective_Date__c</fullName>
        <label>Benefit Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Count__c</fullName>
        <label>Contract Count</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Benefit Request Forms</relationshipLabel>
        <relationshipName>Benfit_Request_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PRF__c</fullName>
        <formula>Proposal_Request_Form__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PRF</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proposal_Request_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposal Request Form</label>
        <referenceTo>PRF__c</referenceTo>
        <relationshipLabel>Benefit Request Forms</relationshipLabel>
        <relationshipName>Benefit_Request_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <label>Next Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Benefit Request Form Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Benefit Request Form</label>
    <nameField>
        <displayFormat>BRF-{000000}</displayFormat>
        <label>Benefit Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Request Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <label>Business Type</label>
        <picklist>
            <controllingField>Division__c</controllingField>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contract_End_Date__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <controllingField>Market_Segment_New__c</controllingField>
            <picklistValues>
                <fullName>51-199 New Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>51-199 Renewals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CFA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FEHBP Account Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Labor Affairs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NCAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State &amp; Municipalities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Healthcare/Education/Par</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic Accounts 1000+</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Underwriting_Entity__c</fullName>
        <description>Where Underwriting is performed.  Usually the location of the company headquarters.</description>
        <label>Underwriting Entity</label>
        <picklist>
            <controllingField>Division__c</controllingField>
            <picklistValues>
                <fullName>CFA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NCAS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>AIA_200</fullName>
        <active>true</active>
        <businessProcess>AIA Large Group Sales Process</businessProcess>
        <description>200+ Opportunity Record Type</description>
        <label>200+</label>
    </recordTypes>
</CustomObject>

src/objects/PRF__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposal Request Forms</relationshipLabel>
        <relationshipName>Proposal_Request_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/classes/AIA_OpportunityTrigger_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class AIA_OpportunityTrigger_Test{
    static testMethod void testMarkOpportunitySold(){
        Test.startTest();       
        Account testacct1 = new Account();
        testacct1.Name = 'TestAccount4';
        testacct1.Type = 'Customer';
        insert testacct1;
        
        Id rt_opp_200= QueryBase.getRecordtypeId('Opportunity', 'AIA_200');
                
         // Opportunity has a NASCO System and an associated NASCO group ID
        Opportunity testOpp1 = new Opportunity();
        testOpp1.RecordTypeId = rt_opp_200;

         
        testOpp1.Name = 'Test Opportunity1';
        testopp1.AccountId = testacct1.Id;
        testOpp1.StageName ='Proposal';    
        testOpp1.CloseDate = Date.today()-90;
        testOpp1.SBU__c = 'Small/Medium';
        testopp1.Market_Segment_New__c = '51-199';
        testopp1.Business_type__c = 'Renewal';
        testopp1.Division__c = '51-199 Renewals';   
        testopp1.Underwriting_Entity__c = 'MD';
        //testopp1.Lead_Rep_Name_User__c = salesUser.Id;
        testOpp1.GeneralProducer__c = 'Direct'; 
        testOpp1.System__c = 'NASCO';    
        testOpp1.NASCO_Acct_ID__c = '12201';   
        testOpp1.Related_Products_Sold__c = 'Test';       
        Date effectiveDate = testOpp1.CloseDate.addDays(35);        
        testOpp1.Effective_Date__c = Date.newInstance(effectiveDate.Year(), effectiveDate.Month(), 1);
        Date contractEndDate = testOpp1.Effective_Date__c+365;
        contractEndDate = Date.newInstance(contractEndDate.Year(), contractEndDate.Month(), 1);
        contractEndDate = contractEndDate.addDays(-1);
        testOpp1.Contract_End_Date__c = contractEndDate;  
        testOpp1.Won_Lost_Reason__c = 'Acquisition';    //TPB 06/06/2014              
        insert testopp1;

        //testOppsList.add(testOpp1);
        
        //insert test record for Proposal Request Form
        PRF__c prf = new PRF__c();
        prf.Name = 'testprf';
        prf.Opportunity__c = testOpp1.id;
        insert prf;
        
        //insert test record for Benefit Request Form
        Benfit_Request_Form__c nbrf = new Benfit_Request_Form__c();
        nbrf.Proposal_Request_Form__c = prf.id;
        nbrf.Opportunity__c = testOpp1.id;
        nbrf.Contract_Count__c = 123;
        nbrf.Benefit_Effective_Date__c = system.today();
        nbrf.Renewal_Date__c = system.today();
        nbrf.Status__c='Sold';
        insert nbrf;
        
         //Update Opportunity to Sold
                             
        Opportunity QueriedOpp = [Select Id,name from Opportunity where id=:testOpp1.Id];
        QueriedOpp.StageName = 'Sold';
        Update QueriedOpp;
        
         Test.stopTest();
               
        }
}