src/objects/AIA_Document__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>File_Net_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Attachment_ID__c</fullName>
        <label>Attachment ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Format__c</fullName>
        <label>Document Format</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <label>Document Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Document_Status__c</fullName>
        <label>Document Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <picklist>
            <picklistValues>
                <fullName>Additional Documentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AIA Account Issue Documentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benefit Design Document</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benefit Request Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Associate Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Associate Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cede Document</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Census Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Screener Questionnaire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Structure Approval Notification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Structure Document</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marked Up Benefit Summary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRF Assignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRF Documentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRF Workplan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Production Id Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Data Analyst Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Data Analyst Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsigned Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mock ID Card</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>File_Net_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposal_Request_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposal Request Form</label>
        <referenceTo>PRF__c</referenceTo>
        <relationshipName>File_Net_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Workplan Assignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benefit Request Form</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Workplan_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Workplan Assignment</label>
        <referenceTo>AIA_Workplan_Assignment__c</referenceTo>
        <relationshipName>File_Net_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AIA Document</label>
    <nameField>
        <displayFormat>FD-{000000}</displayFormat>
        <label>AIA Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AIA Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AIA_Workplan_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Workplan Assignment</relationshipLabel>
        <relationshipName>Workplan_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date_Completed__c</fullName>
        <label>Date Completed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>AIA_Workplan_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposal_Request_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposal Request Form</label>
        <referenceTo>PRF__c</referenceTo>
        <relationshipName>AIA_Workplan_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Sent</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Required</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Workplan Assignment</label>
    <nameField>
        <displayFormat>WT-{000000}</displayFormat>
        <label>Workplan Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workplan Assignment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PRF__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposal Request Forms</relationshipLabel>
        <relationshipName>Proposal_Request_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/classes/AIA_WorkAssignmentFileUploadCX.cls
/********************************************************************************
********************************************************************************    
 *  Class            : AIADocumentUploadController
 *  Author           : Goutham Rapolu
 *  Version History  : 1.0
 *  Creation         : 05/31/16
 *  Description      : This class will have the logic for upload a document from AIA_Workplan_Assignment__c detail page
 *
 ********************************************************************************
 ********************************************************************************/
public with sharing class AIA_WorkAssignmentFileUploadCX {

//Variable Declaration 
public id recordID{get;set;}
public String description {get;set;}
public String fileName {get;set;}
public Blob fileBody {get;set;}
public Boolean isAttachmentSaved {get;set;}
public AIA_Document__c fNetAttachment{get;set;}
public Attachment attObj;
public AIA_Workplan_Assignment__c work_Assignment_Obj{get;set;}
public AIA_Workplan_Assignment__c work_Assignment;


   //constructor initialization
   public AIA_WorkAssignmentFileUploadCX(ApexPages.StandardController controller) {
       recordID =  ApexPages.CurrentPage().getParameters().get('id');
       fNetAttachment = new AIA_Document__c();
       work_Assignment_Obj = new AIA_Workplan_Assignment__c();
   }

    // creates a new AIA_Document record 
    private Database.SaveResult saveCustomAttachment() {

        work_Assignment = new AIA_Workplan_Assignment__c();
        if(recordID != null){
            work_Assignment = [select id,name,Comments__c,Date_Completed__c,Status__c,Proposal_Request_Form__c,Proposal_Request_Form__r.Opportunity__c,Proposal_Request_Form__r.Opportunity__r.AccountID from AIA_Workplan_Assignment__c where id =: recordID limit 1];

        }
        AIA_Document__c fNetDoc = new AIA_Document__c();
        fNetDoc.Document_Name__c = this.fileName;
        if(work_Assignment != null){
            fNetDoc.Proposal_Request_Form__c = work_Assignment.Proposal_Request_Form__c;
            if(work_Assignment.Proposal_Request_Form__r.Opportunity__c != null || work_Assignment.Proposal_Request_Form__r.Opportunity__c !='')
            fNetDoc.Opportunity__c = work_Assignment.Proposal_Request_Form__r.Opportunity__c;
            if(work_Assignment.Proposal_Request_Form__r.Opportunity__r.AccountID != null || work_Assignment.Proposal_Request_Form__r.Opportunity__r.AccountID !='')
            fNetDoc.Account__c = work_Assignment.Proposal_Request_Form__r.Opportunity__r.AccountID ;
            fNetDoc.Source__c = 'Workplan Assignment';
            fNetDoc.Workplan_Assignment__c = work_Assignment.id;
        }
        
        fNetDoc.Document_Status__c = fNetAttachment.Document_Status__c;
        fNetDoc.Document_Type__c = fNetAttachment.Document_Type__c;
        fNetDoc.Active__c = fNetAttachment.Active__c;
        fNetDoc.Start_Date__c = fNetAttachment.Start_Date__c;
        fNetDoc.End_Date__c = fNetAttachment.End_Date__c;
        
        system.debug('fNetDoc'+ fNetDoc);
        // fill out cust obj fields
        return Database.insert(fNetDoc,true);
    }
    
    // create an actual Attachment record
    private Database.SaveResult saveStandardAttachment(Id parentId) {
        Database.SaveResult result;
        
        Attachment attachment = new Attachment();
        attachment.body = this.fileBody;
        attachment.name = this.fileName;
        attachment.description = description;
        attachment.parentId = parentId;
        
        // insert the attahcment
        result = Database.insert(attachment,true);
        // reset the file for the view state
        fileBody = Blob.valueOf(' ');
        isAttachmentSaved = true;
        
        return result;
    }
    
    /**
    * Upload process is:
    *  1. Insert new AIA_Document__c record
    *  2. Insert new Attachment with the new AIA_Document__c record as parent
    *  3. Update the AIA_Document__c record with the ID of the new Attachment
    **/
    
    public PageReference processUpload() {
        try {
            Database.SaveResult customAttachmentResult = saveCustomAttachment();
        
            if (customAttachmentResult == null || !customAttachmentResult.isSuccess()) {
                ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 
                  'Could not save attachment.'));
                return null;
            }
        
            Database.SaveResult attachmentResult = saveStandardAttachment(customAttachmentResult.getId());
        
            if (attachmentResult == null || !attachmentResult.isSuccess()) {
                ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 
                  'Could not save attachment.'));            
                return null;
            } else {
                // update the AIA Document Object record with some attachment info
                fNetAttachment = new AIA_Document__c();
                fNetAttachment = [select id,account__r.name,Document_Name__c,Document_Type__c,Active__c,End_Date__c,Start_Date__c,Document_Format__c,
                                  Version__c,Attachment_ID__c,Document_Status__c from AIA_Document__c where id = :customAttachmentResult.getId() limit 1];
                String str = fNetAttachment.Document_Name__c;
                list<string> fileExtension = new list<string>();
                fileExtension = str.split('[.]');
                system.debug(fileExtension[0]+'OOOOOO'+fileExtension[1]);
                fNetAttachment.Document_Name__c = fNetAttachment.Document_Type__c+'_'+fileExtension[0];
                fNetAttachment.Attachment_ID__c = attachmentResult.getId();
                fNetAttachment.Document_Format__c = fileExtension[1];
                update fNetAttachment;
                
                work_Assignment.Status__c ='Completed';
                work_Assignment.Date_Completed__c = system.now();
                work_Assignment.Comments__c = work_Assignment_Obj.Comments__c;
                update work_Assignment;
                system.debug('Update fNetAttachment'+ fNetAttachment);
            }
        
        } catch (Exception e) {
            ApexPages.AddMessages(e);
            return null;
        }
        pageReference pg = new pageReference('/'+recordID);
        pg.setRedirect(true);
        return pg;
    }
    
    public pageReference cancelButton(){
        pageReference pg = new pageReference('/'+recordID);
        pg.setRedirect(true);
        return pg;
    }   

}