src/objects/AIA_Implementation__c.object
<CustomObject>
    <fields>
        <fullName>Generate_Workplan_Stages__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Generate Workplan Stages</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>AIA_Post_Sales_Implementation</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In-Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Workplan_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Workplan Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AIA_Workplan_Type__c.Used_For__c</field>
                <operation>equals</operation>
                <value>Implementation</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AIA_Workplan_Type__c</referenceTo>
        <relationshipLabel>Implementations</relationshipLabel>
        <relationshipName>Implementations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Implementation</label>
    <nameField>
        <displayFormat>IMP-{000000}</displayFormat>
        <label>Implementation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Implementations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Workplan_Stage__c.object
<CustomObject>
    <fields>
        <fullName>All_Assignments_Must_Be_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>All Assignments Must Be Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Display_Order__c</fullName>
        <label>Display Order</label>
        <precision>14</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Implementation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation</label>
        <referenceTo>AIA_Implementation__c</referenceTo>
        <relationshipLabel>Workplan Stage</relationshipLabel>
        <relationshipName>AIA_Workplan_Stage1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>AIA_Workplan_Stage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Workplan_Stage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Workplan Stage</label>
        <referenceTo>Workplan_Stage__c</referenceTo>
        <relationshipLabel>Workplan Stage</relationshipLabel>
        <relationshipName>Workplan_Stage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Workplan_Type_Stage__c</fullName>
        <formula>TEXT(Workplan_Type_Stage__r.Stage_Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Workplan Type Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Required</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Workplan_Stage__c</fullName>
        <formula>TEXT(Workplan_Type_Stage__r.Stage__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Workplan Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Workplan_Type_Stage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Workplan Type Stage</label>
        <referenceTo>Workplan_Type_Stage__c</referenceTo>
        <relationshipName>Workplan_Type_Stage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Workplan_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Workplan Type</label>
        <referenceTo>AIA_Workplan_Type__c</referenceTo>
        <relationshipLabel>Workplan Stage</relationshipLabel>
        <relationshipName>Workplan_Stage</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Workplan Stage</label>
    <nameField>
        <displayFormat>WS-{000000}</displayFormat>
        <label>Workplan Stage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workplan Stage</pluralLabel>
    <recordTypes>
        <fullName>Process</fullName>
        <active>true</active>
        <label>Process</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Workplan_Type_Stage__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>All_Assignments_Must_Be_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>All Assignments Must Be Completed before another stage can be started (set to in progress)</inlineHelpText>
        <label>All Assignments Must Be Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Display_Order__c</fullName>
        <formula>IF ( RecordType.DeveloperName = &apos;Process&apos;, Sequence_Number__c, Parent_Workplan_Type_Stage__r.Sequence_Number__c + (Sequence_Number__c / 100))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Display Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Workplan_Type_Stage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Workplan Type Stage</label>
        <referenceTo>Workplan_Type_Stage__c</referenceTo>
        <relationshipLabel>Workplan Type Stage</relationshipLabel>
        <relationshipName>Workplan_Type_Stages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Workplan_Type__c</fullName>
        <label>Workplan Type</label>
        <referenceTo>AIA_Workplan_Type__c</referenceTo>
        <relationshipLabel>Workplan Type Stage</relationshipLabel>
        <relationshipName>AIA_Workplan_Type_Stage</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Workplan Type Stage</label>
    <nameField>
        <displayFormat>WTS-{00000}</displayFormat>
        <label>Workplan Type Stage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workplan Type Stage</pluralLabel>
    <recordTypes>
        <fullName>Process</fullName>
        <active>true</active>
        <label>Process</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AIA_Workplan_Implementation.cls
/*=========================================================================================
 * Date     : 05/31/2016
 * Developer    : chidananda Nagaaj
  * Purpose      : This class is the extension point of the All the AIA_Implementation Trigger Framework - 
                                 ImplementationTriggerHandler..
 *                
 *               
 *
 *=========================================================================================
 *                                 Update History
 *                                 ---------------
 * Date       Developer         Description
 *===========+============+================================================================
 * 05/31/16  |  GN   | Initial Version                                         
 *           |        | 
 *===========+============+================================================================
* @This Method is called from ImplementationTriggerHandler class - AfterInsert Method 
* @This Method that allows workplan stages(Process & Sub-process records) to be created automatically on that Implementation w.r.t Workplan type Assigned (Refer above method) 
* @param ListImp - Input the list of Implementations 
* @Output - Creating the Workplan stages(Process & Sub-process records) and updating the sub-process records with their respective parent process(Hint:sub-processes roll up to a particular process) 
*/

public class AIA_Workplan_Implementation
{

public void createWorkplanStages(List<AIA_Implementation__c> listImp)
    {
    
     
        //Getting the RecordTypes -Id's of - WorkPlan Type Stage object 
        // TODO: Add comments for each of the variables.
        Schema.DescribeSObjectResult WPTSdSobjres = Schema.SObjectType.Workplan_Type_Stage__c; 
        Map<String,Schema.RecordTypeInfo> WPTSRecordType = WPTSdSobjres.getRecordTypeInfosByName();
        Id ProcesswptsRtid = WPTSRecordType.get('Process').getRecordTypeId();                          //Getting the Process RecordTypeID
        Id SubProcesswptsRtid = WPTSRecordType.get('Sub-Process').getRecordTypeId();                   //Getting the Sub-Process RecordTypeID
        
        //Getting the RecordTypes -Id's of - WorkPlan Stage  object
        Schema.DescribeSObjectResult WPSdSobjres = Schema.SObjectType.Workplan_Stage__c; 
        Map<String,Schema.RecordTypeInfo> WPSRecordType = WPSdSobjres.getRecordTypeInfosByName(); 
        Id ProcesswpsRtid = WPSRecordType.get('Process').getRecordTypeId();                             //Getting the Process RecordTypeID
        Id SubProcesswpsRtid = WPSRecordType.get('Sub-Process').getRecordTypeId();                      //Getting the Sub-Process RecordTypeID
            
        // TODO: Add comment for what each of these variables stores and what it is used for
        List<AIA_Implementation__c> opplist = new List<AIA_Implementation__c>();                                                  //List of opportunities 
        Map<id,List<Workplan_Type_Stage__c>> wptidwptstagesMap = new Map<id,List<Workplan_Type_Stage__c>>();  //Map for id's and list of WorkPlan Type Stage
        Set<id> wpTypeidset = new Set<id>();                                                                  //set of id's to get opp Id's which has workplan type's
        List<Workplan_Stage__c> tocreate = new List<Workplan_Stage__c>();                                     // List to create WorkPlan Stages for output 
        Map<id,Workplan_Type_Stage__c> wptsMap = new Map<id,Workplan_Type_Stage__c>();                        // Map for workplan Type Stages and their Id's
        
        /* Add all AIA_Implementation__c that have a workplan type to the Opplist list*/
        for(AIA_Implementation__c opp: listImp)
        {
            if(opp.Workplan_Type__c !=null)
            {
                opplist.add(opp);                          //Adding all the list of opp where workplan type not equals null
                wpTypeidset.add(opp.Workplan_Type__c);     //Adding all the set of opp Id's which has workplan type's
            }
        }
        
        // If list is not empty  --- Make changes to All ****************************check this Line***********************
        //if(wpTypeidset != null && wpTypeidset.size()>0)
        if (!wpTypeIdset.isEmpty())
        {
            //Query the particular set of workPlan type Stage id's  from above "wpTypeidset"
            List<Workplan_Type_Stage__c> wptstages=[Select id,RecordTypeId,Display_Order__c,Workplan_Type__c,All_Assignments_Must_Be_Completed__c,Parent_Workplan_Type_Stage__c from Workplan_Type_Stage__c where Workplan_Type__c in :wpTypeidset and Active__c=true ];
            // Add all Workplan Type Stages field values to Map
            wptsMap.putAll(wptstages);
            
            //Looping WorkPlan Type Stage from above list -"wptstages" and adding them to map
            for(Workplan_Type_Stage__c obj:wptstages){
                if(wptidwptstagesMap.containskey(obj.Workplan_Type__c))
                {
                    wptidwptstagesMap.get(obj.Workplan_Type__c).add(obj);                                  //Getting workplan type into Map
                }
                else{
                    wptidwptstagesMap.put(obj.Workplan_Type__c,new List<Workplan_Type_Stage__c>{obj});     // Else creating the new list of Workplan type Stages into Map
                }
            }
        }
        
   
        /*Looping each AIA_Implementation__c,If opp contains particular Workplan type-Then creating Workplan stages underneath opp W.R.T WorkPlan type Stages*/  
        for(AIA_Implementation__c opp:opplist)
        {
         if(opp.Generate_Workplan_Stages__c)
         {
            If(wptidwptstagesMap.containskey(opp.Workplan_Type__c))
            {                              
                //Checking whether opp.Workplan_Type__c  is/Contains in wptidwptstagesMap or not 
                for(Workplan_Type_Stage__c wps:wptidwptstagesMap.get(opp.Workplan_Type__c))
                {      
                    //if it contains Looping WorkPlan type stages and creating Workplan stages with some Mapping
                    //Assigning the Values to Workplan stage from Workplan Type Stage
                    Workplan_Stage__c ws       = new Workplan_Stage__c();
                    ws.Opportunity__c          = opp.Opportunity__c;
                    ws.Implementation__c       = opp.id;
                    ws.Workplan_Type_Stage__c  = wps.id;
                    ws.Workplan_Type__c        = wps.Workplan_Type__c;
                    ws.Status__c               = 'Not Started';
                    ws.All_Assignments_Must_Be_Completed__c = wps.All_Assignments_Must_Be_Completed__c;
                    ws.Display_Order__c        = wps.Display_Order__c;
                    
                    //Assigning the Process RecordTypeId's of (Workplan_Type_Stage__c) to  process RecordTypeId's - WS(workplan_stage__c)
                    if(wps.RecordTypeId ==ProcesswptsRtid )
                    {
                        ws.RecordTypeId = ProcesswpsRtid ;
                    }
                    //Assigning the Sub-Process RecordTypeId's of (Workplan_Type_Stage__c) to  sub-process RecordTypeId's-(workplan stage)
                    else if(wps.RecordTypeId ==SubProcesswptsRtid )
                    {
                        ws.RecordTypeId = SubProcesswpsRtid ;
                    }
                    tocreate.add(ws);        //Adding the list of Workplan stages
                }
            }
            }
        }
        
        /*Creating Workplan stage */
        //if(tocreate != null && tocreate.size()>0)
        if (!toCreate.isEmpty())
        {
            insert tocreate;
            Map<id,id> parentMap = new Map<id,id>();
            for(Workplan_Stage__c ws:tocreate)
            {
                if(ws.RecordTypeId == ProcesswpsRtid)
                {
                    parentMap.put(ws.Workplan_Type_Stage__c, ws.id);
                }
            }
            //Updating the Sub-Processes records with their parent workplan type stages
            for(Workplan_Stage__c ws:tocreate){
                if(ws.RecordTypeId == SubProcesswpsRtid  && ws.Workplan_Type_Stage__c != null && wptsMap.containskey(ws.Workplan_Type_Stage__c) )
                {
                    ws.Parent_Workplan_Stage__c = parentMap.get(wptsMap.get(ws.Workplan_Type_Stage__c).Parent_Workplan_Type_Stage__c);
                }
            }
            
            try{
                update tocreate; 
            }
            catch(Exception ex){
                System.debug(' \n CLog : '+ex.getMessage());
            }
        }
      }
  }