src/objects/AIA_Workplan_Type__c.object
<CustomObject>
    <label>Workplan Type</label>
    <nameField>
        <displayFormat>WPT-{000000}</displayFormat>
        <label>Workplan Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workplan Type</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AIA_Workplan_Type_Task__c.object
<CustomObject>
    <fields>
        <fullName>Workplan_Type_Stage__c</fullName>
        <label>Workplan Type Stage</label>
        <referenceTo>Workplan_Type_Stage__c</referenceTo>
        <relationshipName>Workplan_Type_Task</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Workplan Type Assignment</label>
    <nameField>
        <displayFormat>WTA-{000000}</displayFormat>
        <label>Workplan Type Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workplan Type Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Workplan_Type_Stage__c.object
<CustomObject>
    <label>Workplan Type Stage</label>
    <nameField>
        <displayFormat>WTS-{00000}</displayFormat>
        <label>Workplan Type Stage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workplan Type Stage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AIA_WorkplanTypeAssignmentTrigger_Test.cls
@isTest
public class AIA_WorkplanTypeAssignmentTrigger_Test{
    public static testmethod void mytest1(){
        //create Group for Queues
        List<String> names = new List<string>{'TestQ1','TestQ2','TestQ3','TestQ4','TestQ5','TestQ6'};
        List<Group> Glst = AIA_TestUtil.createGroup(names,'Queue');
        //create Queues with Group Ids
        List<QueuesObject> Qlst= AIA_TestUtil.createQueues(Glst,'Lead');
        
        Test.StartTest();
        Profile p = [SELECT Id FROM Profile WHERE Name='AIA 200+ Standard User - Custom'];
         
        User u = new User(Alias = 'TAlias', Email='TestUser1@testorg.com',
        EmailEncodingKey='UTF-8', LastName='TestingUSer', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p.Id,
        TimeZoneSidKey='America/Los_Angeles', UserName='TestingUser1@testorg.com');
        
        System.runAs(u){
            //create Work plan Type 
            AIA_Workplan_Type__c WPT = AIA_TestUtil.createWPT();
            //create work plan type stage with work plan type Id
            Workplan_Type_Stage__c WPTS = AIA_TestUtil.createWPTS(WPT.Id);
            
             try{
                //create Work plan Type Task With Work Plan Type Stage Id
                List<AIA_Workplan_Type_Task__c> WPTTlst = AIA_TestUtil.createWPTT(WPTS.Id);
                
                List<AIA_Workplan_Type_Task__c> lst1 = [select Id from AIA_Workplan_Type_Task__c];
                system.assertequals(3,lst1.size());
            
                //update Work Plan Task Type With Existing Records
                List<AIA_Workplan_Type_Task__c> UPWPTTlst = AIA_TestUtil.updateWPTT(WPTTlst);
             }catch( exception e ){
                RETURN;   
            } 
        }
        
        Profile p1 = [SELECT Id FROM Profile WHERE Name='AIA RUL Custom'];
         
        User u1 = new User(Alias = 'TAlias2', Email='TestUser2@testorg.com',
        EmailEncodingKey='UTF-8', LastName='TestingUSer', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p1.Id,
        TimeZoneSidKey='America/Los_Angeles', UserName='TestingUser2@testorg.com');
        
        System.runAs(u1){
            //create Work plan Type 
            AIA_Workplan_Type__c WPT = AIA_TestUtil.createWPT();
            //create work plan type stage with work plan type Id
            Workplan_Type_Stage__c WPTS = AIA_TestUtil.createWPTS(WPT.Id);
            
             
             try{
                //create Work plan Type Task With Work Plan Type Stage Id
                List<AIA_Workplan_Type_Task__c> WPTTlst = AIA_TestUtil.createWPTT(WPTS.Id);
                
                List<AIA_Workplan_Type_Task__c> lst1 = [select Id from AIA_Workplan_Type_Task__c];
                system.assertequals(6,lst1.size());
            
                //update Work Plan Task Type With Existing Records
                List<AIA_Workplan_Type_Task__c> UPWPTTlst = AIA_TestUtil.updateWPTT(WPTTlst);
             }catch( exception e ){
                RETURN;   
            }
             
        }
        Test.StopTest();
    }
}