src/objects/AIA_Workplan_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Proposal_Request_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposal Request Form</label>
        <referenceTo>PRF__c</referenceTo>
        <relationshipName>AIA_Workplan_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Workplan Assignment</label>
    <nameField>
        <displayFormat>WT-{000000}</displayFormat>
        <label>Workplan Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workplan Assignment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AIA_WPAController.cls
//===================================================================================
//Date: 04/19/2016
//Developer: Sree Harsha Akkala
//Purpose: Saves the Workplan Assignment and links it with Proposal Request Form.
//=========================================================================================
// Update History
// Date         Developer               Description
//==================================================================================
//04/19/2016    Sree Harsha Akkala      Initial Development
//==================================================================================
public class AIA_WPAController {
    
    public AIA_Workplan_Assignment__c wpa{get;set;}
    /**
     * Sets the owner to current user.  
     * @Constructor AIA_WPAController    
    */
    public AIA_WPAController(ApexPages.StandardController controller) {
        wpa = new AIA_Workplan_Assignment__c();
        wpa.ownerId=userinfo.getuserId();
    }
     /**
     * Saves the Workplan Assignment and links it with Proposal Request Form.   
     * @method save  
    */  
    public pagereference save(){
        try{
            wpa.Proposal_Request_Form__c= apexpages.currentpage().getparameters().get('PRFid');
            
            insert wpa;
        }
        catch(exception e){
            system.debug(e.getMessage());
        }        
        return new pagereference('https://carefirst--devAIA.cs44.my.salesforce.com/'+wpa.id);        
    }    
            
}