src/objects/AIA_Benefit_Design__c.object
<CustomObject>
    <label>Benefit Design</label>
    <nameField>
        <displayFormat>BD-{00000000}</displayFormat>
        <label>Benefit Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Design</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AIA_Document__c.object
<CustomObject>
    <fields>
        <fullName>Proposed_Products__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposed Products</label>
        <referenceTo>Proposed_Products__c</referenceTo>
        <relationshipName>File_Net_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AIA Document</label>
    <nameField>
        <displayFormat>FD-{000000}</displayFormat>
        <label>AIA Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AIA Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AIA_Implementation__c.object
<CustomObject>
    <label>Implementation</label>
    <nameField>
        <displayFormat>IMP-{000000}</displayFormat>
        <label>Implementation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Implementations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Benfit_Request_Form__c.object
<CustomObject>
    <description>New object for AIA - This object stores the information that is needed for a quote</description>
    <fields>
        <fullName>PRF__c</fullName>
        <formula>Proposal_Request_Form__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PRF</label>
        <type>Text</type>
    </fields>
    <label>Benefit Request Form</label>
    <nameField>
        <displayFormat>BRF-{000000}</displayFormat>
        <label>Benefit Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Request Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PRF__c.object
<CustomObject>
</CustomObject>

src/objects/Proposed_Products__c.object
<CustomObject>
    <label>Proposed Products</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>Proposed Products Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposed Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AIADocumentUploadController_Test.cls
//===================================================================================
//Date: 06/18/2016
//Developer: Goutham Rapolu
//Purpose: Test class for AIADocumentUploadController
//==================================================================================
// Update History
// Date         Developer               Description
// 
//==================================================================================
//06/18/2016    Goutham Rapolu     Initial Development
//==================================================================================

@isTest
private class AIADocumentUploadController_Test {
   
    Public static testmethod void TestAccount() {
    	 List<AIA_Document__c> aiaDocList = new List<AIA_Document__c>();
	     User u = AIA_TestUtil.createTestUser();
	      System.runAs(u) {    
	      	 // creating AIA Document
	      	 AIA_Document__c aiaDoc = AIA_TestUtil.createAIADocument();
	      	 system.assertNotEquals(null,aiaDoc.id);
	         
	      	 aiaDocList.add(aiaDoc);
	      	 
			 // Create Account
	         Account a = AIA_TestUtil.CreateAccount('TestAccount'); 
	         system.assertNotEquals(null,a.id);
	         string cv = 'document';
		     Blob cvBlob = Blob.toPdf('document');
		     
	         Apexpages.Currentpage().getParameters().put('id',a.id);
	         ApexPages.StandardSetController testController = new ApexPages.StandardSetController(aiaDocList);
	         AIADocumentUploadController controllerObj = new AIADocumentUploadController(testController);
	         controllerObj.fileBody = cvBlob;
	         controllerObj.fileName = 'TestDoc.pdf';
	         controllerObj.description = 'test Document';
	         controllerObj.processUpload();
	         controllerObj.cancelButton();  
	      }      
    }
    
    Public static testmethod void TestOpportunity() {
    	 List<AIA_Document__c> aiaDocList = new List<AIA_Document__c>();
    	 User u = AIA_TestUtil.createTestUser();
    	 System.runAs(u) { 
    	 	 // creating AIA Document
	      	 AIA_Document__c aiaDoc = AIA_TestUtil.createAIADocument();
	      	 system.assertNotEquals(null,aiaDoc.id);
	      	 aiaDocList.add(aiaDoc); 
	      	 
			 // Create Account
	         Account a = AIA_TestUtil.CreateAccount('TestAccount');
	         system.assertNotEquals(null,a.id);
	         // Create Opportunity
	         Opportunity o = AIA_TestUtil.AIA_createopportunity(a.Id);
	         system.assertNotEquals(null,o.id);
	         Apexpages.Currentpage().getParameters().put('id',o.id);
	         ApexPages.StandardSetController testController = new ApexPages.StandardSetController(aiaDocList);
	         AIADocumentUploadController controllerObj = new AIADocumentUploadController(testController);
	         controllerObj.processUpload();
	         controllerObj.cancelButton();
    	 }
    }
    
    Public static testmethod void TestBenfitRequestForm() {
    	 List<AIA_Document__c> aiaDocList = new List<AIA_Document__c>();
	     User u = AIA_TestUtil.createTestUser();
	     System.runAs(u) {  
	     	// creating AIA Document
	      	 AIA_Document__c aiaDoc = AIA_TestUtil.createAIADocument();
	      	 system.assertNotEquals(null,aiaDoc.id);
	      	 aiaDocList.add(aiaDoc);
	      	 
			 // Create Account
	         Account a = AIA_TestUtil.CreateAccount('TestAccount');
	         system.assertNotEquals(null,a.id);
	         
	         // Create Opportunity
	         Opportunity o = AIA_TestUtil.AIA_createopportunity(a.Id);
	         system.assertNotEquals(null,o.id);
	         
	         // Create PRF
	         PRF__c p = AIA_TestUtil.CreatePRF(o.Id);
	         system.assertNotEquals(null,p.id);
	         Benfit_Request_Form__c brf = AIA_TestUtil.CreateBRF(p.id,a.id);
	         system.assertNotEquals(null,brf.id);
	         Apexpages.Currentpage().getParameters().put('id',brf.id);
	         ApexPages.StandardSetController testController = new ApexPages.StandardSetController(aiaDocList);
	         AIADocumentUploadController controllerObj = new AIADocumentUploadController(testController);
	         controllerObj.processUpload();
	         controllerObj.cancelButton();
	     }
    }
    
   Public static testmethod void TestPRF(){
   	     List<AIA_Document__c> aiaDocList = new List<AIA_Document__c>();
	     User u = AIA_TestUtil.createTestUser();
	     System.runAs(u) { 
	     	// creating AIA Document
	      	 AIA_Document__c aiaDoc = AIA_TestUtil.createAIADocument();
	      	 system.assertNotEquals(null,aiaDoc.id);
	      	 aiaDocList.add(aiaDoc);
	      	  
			 // Create Account
	         Account a = AIA_TestUtil.CreateAccount('TestAccount');
	         system.assertNotEquals(null,a.id);
	         // Create Opportunity
	         Opportunity o = AIA_TestUtil.AIA_createopportunity(a.Id);
	         system.assertNotEquals(null,o.id);
	         // Create PRF
	         PRF__c p = AIA_TestUtil.CreatePRF(o.Id);
	         system.assertNotEquals(null,p.id);
	         Apexpages.Currentpage().getParameters().put('id',p.id);
	         ApexPages.StandardSetController testController = new ApexPages.StandardSetController(aiaDocList);
	         AIADocumentUploadController controllerObj = new AIADocumentUploadController(testController);
	         controllerObj.processUpload();
	         controllerObj.cancelButton();
	     }
    }
    
    Public static testmethod void TestAIAImplementation() {
    	 List<AIA_Document__c> aiaDocList = new List<AIA_Document__c>();
	     User u = AIA_TestUtil.createTestUser();
	      System.runAs(u) {    
	      	 // creating AIA Document
	      	 AIA_Document__c aiaDoc = AIA_TestUtil.createAIADocument();
	      	 system.assertNotEquals(null,aiaDoc.id);
	      	 aiaDocList.add(aiaDoc);
	      	 
			 // Create Account
	         Account a = AIA_TestUtil.CreateAccount('TestAccount'); 
	         system.assertNotEquals(null,a.id);
	         Opportunity o = AIA_TestUtil.AIA_createopportunity(a.Id);
	         system.assertNotEquals(null,o.id);
	         AIA_Implementation__c aiaImp = AIA_TestUtil.CreateImp(o.id);
	         system.assertNotEquals(null,aiaImp.id);
	         Apexpages.Currentpage().getParameters().put('id',aiaImp.id);
	         ApexPages.StandardSetController testController = new ApexPages.StandardSetController(aiaDocList);
	         AIADocumentUploadController controllerObj = new AIADocumentUploadController(testController);
	         controllerObj.processUpload();
	         controllerObj.cancelButton();  
	      }      
    }
    
    Public static testmethod void TestProposedProducts() {
    	 List<AIA_Document__c> aiaDocList = new List<AIA_Document__c>();
	     User u = AIA_TestUtil.createTestUser();
	      System.runAs(u) {    
	      	 // creating AIA Document
	      	 AIA_Document__c aiaDoc = AIA_TestUtil.createAIADocument();
	      	 system.assertNotEquals(null,aiaDoc.id);
	      	 aiaDocList.add(aiaDoc);
	      	 
			 // Create Account
	         Account a = AIA_TestUtil.CreateAccount('TestAccount');
	         system.assertNotEquals(null,a.id);
	         // Create Opportunity
	         Opportunity o = AIA_TestUtil.AIA_createopportunity(a.Id);
	         system.assertNotEquals(null,o.id);
	         // Create PRF
	         PRF__c p = AIA_TestUtil.CreatePRF(o.Id);
	         system.assertNotEquals(null,p.id);
	         Benfit_Request_Form__c brf = AIA_TestUtil.CreateBRF(p.id,a.id);
	         system.assertNotEquals(null,brf.id);
	         Proposed_Products__c aiaImp = AIA_TestUtil.createProposedProducts(brf.id);
	         system.assertNotEquals(null,aiaImp.id);
	         Apexpages.Currentpage().getParameters().put('id',aiaImp.id);
	         ApexPages.StandardSetController testController = new ApexPages.StandardSetController(aiaDocList);
	         AIADocumentUploadController controllerObj = new AIADocumentUploadController(testController);
	         controllerObj.processUpload();
	         controllerObj.cancelButton();  
	      }      
    }
    
    Public static testmethod void TestAIABenefitDesign() {
    	 List<AIA_Document__c> aiaDocList = new List<AIA_Document__c>();
	     User u = AIA_TestUtil.createTestUser();
	      System.runAs(u) {    
	      	 // creating AIA Document
	      	 AIA_Document__c aiaDoc = AIA_TestUtil.createAIADocument();
	      	 system.assertNotEquals(null,aiaDoc.id);
	      	 aiaDocList.add(aiaDoc);
	      	 
			 // Create Account
	         Account a = AIA_TestUtil.CreateAccount('TestAccount');
	         system.assertNotEquals(null,a.id);
	         // Create Opportunity
	         Opportunity o = AIA_TestUtil.AIA_createopportunity(a.Id);
	         system.assertNotEquals(null,o.id);
	         // Create PRF
	         
	         AIA_Benefit_Design__c aiaBD = AIA_TestUtil.createBenefitDesign(o.id);
	         system.assertNotEquals(null,aiaBD.id);
	         Apexpages.Currentpage().getParameters().put('id',aiaBD.id);
	         ApexPages.StandardSetController testController = new ApexPages.StandardSetController(aiaDocList);
	         AIADocumentUploadController controllerObj = new AIADocumentUploadController(testController);
	         controllerObj.processUpload();
	         controllerObj.cancelButton();  
	      }      
    }
}