src/objects/AIA_Document__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Approvals</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Benefit_Request_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Benefit Request Form</label>
        <referenceTo>Benfit_Request_Form__c</referenceTo>
        <relationshipName>File_Net_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <picklist>
            <picklistValues>
                <fullName>Additional Documentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AIA Account Issue Documentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benefit Design Document</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benefit Request Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Associate Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Associate Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cede Document</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Census Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Screener Questionnaire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Structure Approval Notification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Structure Document</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marked Up Benefit Summary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRF Assignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRF Documentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRF Workplan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Production Id Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Data Analyst Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Data Analyst Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsigned Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mock ID Card</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>File_Net_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposal_Request_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposal Request Form</label>
        <referenceTo>PRF__c</referenceTo>
        <relationshipName>File_Net_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AIA Document</label>
    <nameField>
        <displayFormat>FD-{000000}</displayFormat>
        <label>AIA Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AIA Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Benfit_Request_Form__c.object
<CustomObject>
    <description>New object for AIA - This object stores the information that is needed for a quote</description>
    <fields>
        <fullName>ARC_Approval_Required__c</fullName>
        <formula>(Count_of_CDH_Products__c &gt;0 || Count_of_Custom_Products__c &gt; 0 || EGWP__c = true || FlexLink__c = true) 

&amp;&amp; 

(((MHP_Required__c = &quot;Yes&quot; ) &amp;&amp; ( MHP_Test_Result__c = &quot;Pass&quot;)) 

|| 
( (MHP_Required__c = &apos;Yes&apos;) &amp;&amp; (MHP_Test_Result__c = &apos;Deferred&apos;) || NOT(MHP_Required__c = &apos;Yes&apos;)))</formula>
        <label>ARC Approval Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ARC_Approval_Status__c</fullName>
        <description>ARC Approval Status</description>
        <label>ARC Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved by Committee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by Committee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Decision</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Escalated_to_Senior_Management__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Escalated to Senior Management</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>File_Net_Doc_Id__c</fullName>
        <label>File Net Doc Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Benefit Request Forms</relationshipLabel>
        <relationshipName>Benfit_Request_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PRF__c</fullName>
        <formula>Proposal_Request_Form__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PRF</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proposal_Request_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposal Request Form</label>
        <referenceTo>PRF__c</referenceTo>
        <relationshipLabel>Benefit Request Forms</relationshipLabel>
        <relationshipName>Benefit_Request_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Senior_Management_Approved_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Senior Management Approved By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Benefit_Request_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Benefit Request Form Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Who_Marks_Sold__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Who_Marks_Sold</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Benefit_Request_Forms1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Benefit Request Form</label>
    <nameField>
        <displayFormat>BRF-{000000}</displayFormat>
        <label>Benefit Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Request Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PRF__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposal Request Forms</relationshipLabel>
        <relationshipName>Proposal_Request_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/classes/AIA_BRFTriggerHandler.cls
/********************************************************************************
********************************************************************************    
 *  Class            : AIA BRF Trigger Handler
 *  Author           : Rajesh Pennam
 *  Version History  : 1.0
 *  Creation         : 05/09/16
 *  Description      : This class will have the logic for trigger (BRF Trigger). If the BRF form is
 *                     created from Proposal Request form then the Opportunity of the PRF will be 
 *                     populated to the Opportunity of BRF  

 *
 ********************************************************************************
 ********************************************************************************/

public class AIA_BRFTriggerHandler  extends TriggerHandler {
    
     public AIA_BRFTriggerHandler() {}
    
        /* context override */
    protected override void beforeInsert() {
        updateSeniorManagement((list<Benfit_Request_Form__c>) trigger.new);
        AIA_BRFTriggerHelper.accountNameUpdate((list<Benfit_Request_Form__c>) trigger.new,(Map<id,Benfit_Request_Form__c>) trigger.oldMap);
    }
    
    protected override void beforeUpdate() {    
        updateSeniorManagement((list<Benfit_Request_Form__c>) trigger.new);
        ValidateSoldBRF((list<Benfit_Request_Form__c>) trigger.new,(Map<id,Benfit_Request_Form__c>) trigger.newmap,(Map<id,Benfit_Request_Form__c>) trigger.oldmap);
        AIA_BRFTriggerHelper.accountNameUpdate((list<Benfit_Request_Form__c>) trigger.new,(Map<id,Benfit_Request_Form__c>) trigger.oldMap);
    }
        
    
    protected override void afterInsert() {
        ValidateSoldBRF((list<Benfit_Request_Form__c>) trigger.new,(Map<id,Benfit_Request_Form__c>) trigger.newmap,(Map<id,Benfit_Request_Form__c>) trigger.oldmap);
        updateOpportunityOnBRF((list<Benfit_Request_Form__c>) trigger.new);
        //AIA_BRFTriggerHelper.accountNameUpdate((list<Benfit_Request_Form__c>) trigger.new,(Map<id,Benfit_Request_Form__c>) trigger.oldMap);
        if(AIA_BRFTriggerHelper.BRFListForEmail != null && AIA_BRFTriggerHelper.BRFListForEmail.size()>0 && AIA_BRFTriggerHelper.accIDs != null && AIA_BRFTriggerHelper.accIDs.size()>0)
        AIA_BRFTriggerHelper.processEmail(AIA_BRFTriggerHelper.BRFListForEmail,AIA_BRFTriggerHelper.accIDs);
    }
    
    protected override void afterUpdate() {
        
    }
    /**
    * @Author : Rajesh Pennam
    * @param  : This method is used to update the oppotunity of BRF from PRF
    * @param  : List<Benfit_Request_Form__c> brflst
    * @Output : This method inserts the opportunity on BRF from PRF
    * @return the list of lineitem sobjects 
    */  
    public static List<Benfit_Request_Form__c> UpdateBRFLst = new List<Benfit_Request_Form__c>();
    public static set<Id> PRFids = new set<Id>();
    public static List<PRF__c> PRFLst = new List<PRF__c>();
 
   public static void updateOpportunityOnBRF(List<Benfit_Request_Form__c> brflst){
        for(Benfit_Request_Form__c brf: brflst){
            PRFids.add(brf.Proposal_Request_Form__c);
        }
        
        //PRF List will have the id and the Opportunity of PRF
        PRFLst = [select id,Opportunity__c from PRF__c where id IN :PRFids];
        
        //This loop makes the Opportunity of PRF to Populate to Opportunity of BRF
        for(Benfit_Request_Form__c brf: brflst){
            for(PRF__c prf: PRFLst){
                system.debug('PRF opportunity is '+prf.Opportunity__c);
                if(prf.Opportunity__c != null && brf.Proposal_Request_Form__c != null && brf.Proposal_Request_Form__c == prf.id){
                    Benfit_Request_Form__c nbrf = new Benfit_Request_Form__c();
                    nbrf.id = brf.id;
                    nbrf.Proposal_Request_Form__c = prf.id;
                    nbrf.Opportunity__c = prf.Opportunity__c;
                    UpdateBRFLst.add(nbrf);
                }
            }
        }
        
        //Exception Handling
        
        try{
            if(UpdateBRFLst.size()>0 && UpdateBRFLst != null)
                update UpdateBRFLst;
        }catch(DMLException ex){
            system.debug(ex+'');
        }
    }
    
    /**
* @Author: Sree Harsha Akkala
* @This Method is called from BRFTrigger during insertion or updation of BRF
* @This method - The method tracks who has set the ARC approval status 
* @param -  list<Benfit_Request_Form__c> 
* @Output - Sets the Senior Management Approved by to the current user
*/    
public static void updateSeniorManagement(list<Benfit_Request_Form__c> brfList){
     for(Benfit_Request_Form__c brf:brfList){        
        if((brf.ARC_Approval_Status__c == AIA_Constants.APPROVED_BY_COMMITTEE || brf.ARC_Approval_Status__c==AIA_Constants.REJECTED_BY_COMMITTEE) &&(brf.Escalated_to_Senior_Management__c)){            
            brf.Senior_Management_Approved_By__c = userinfo.getuserId(); //Sets the seniormanagement approved by to current user
        }
        if(brf.status__c=='Sold')
        brf.Who_Marks_Sold__c   = userinfo.getuserid(); //tracks who has set the brf to Sold(used in email alert of approval process) 
                
    }
}


/**
* @Author: Sree Harsha Akkala
* @This Method is called from BRFTrigger during insertion or updation of BRF
* @This method - The method validates when the BRF has to be set to sold
* @param -  list<Benfit_Request_Form__c> 
* @Output - Display an error message if set to sold without signed Quote or Approved Unsigned quote
*/
public static void ValidateSoldBRF(list<Benfit_Request_Form__c> newbrfList,Map<id,Benfit_Request_Form__c> newBRFMap,Map<id,Benfit_Request_Form__c> oldBRFMap){
    list<Benfit_Request_Form__c> brfList = new list<Benfit_Request_Form__c>();
    set<id> brfIdSet = new set<id>();
    for(Benfit_Request_Form__c brf:newbrfList){
        if(oldBRFMap!=null){
        if(oldBRFMap.get(brf.id).status__c=='Sold'){
                brf.addError('You cannot  edit the sold BRF record');
        }
        }
        if(brf.Status__c=='Sold'){          
        brfList.add(brf);
        brfIdSet.add(brf.id);
        }
    }
        
    list<Benfit_Request_Form__c> existingBRFList = [select id,name,ARC_Approval_Required__c,ARC_Approval_Status__c,(select id,name,Document_Type__c,Approval_Status__c from File_Net_Documents__r where Document_Type__c!=null) from Benfit_Request_Form__c where id in:BRFIdSet];
    if(existingBRFList.size()>0){        
        for(Benfit_Request_Form__c brf:existingBRFList){ 
            boolean setToSold=false;
            if(brf.File_Net_Documents__r.size()>0){        
                for(AIA_Document__c fd:brf.File_Net_Documents__r){
                    if((fd.Document_Type__c=='Signed Quote' ||  (fd.Document_Type__c=='Unsigned Quote' && fd.Approval_Status__c=='Approved')) ){
                        if((newBRFMap.get(brf.id).ARC_Approval_Required__c==true && newBRFMap.get(brf.id).ARC_Approval_Status__c==AIA_Constants.APPROVED_BY_COMMITTEE)|| newBRFMap.get(brf.id).ARC_Approval_Required__c==false){
                            brf.File_Net_Doc_Id__c=fd.id;
                            newBRFMap.get(brf.id).File_Net_Doc_Id__c=fd.id;
                            setToSold=true;
                        }                       
                    }                    
                }
                if(setToSold==false){
                    newBRFMap.get(brf.id).addError('You cannot set the BRF to sold');
                }
                    
            }
            else{                
                newBRFMap.get(brf.id).addError('You cannot set the BRF to sold');
            }
              
        }
          
    }
}
}