src/objects/AIA_Implementation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Implementations</relationshipLabel>
        <relationshipName>Implementations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Benefit_Request_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Benefit Request Form</label>
        <referenceTo>Benfit_Request_Form__c</referenceTo>
        <relationshipLabel>Implementations</relationshipLabel>
        <relationshipName>Implementations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>AIA_Post_Sales_Implementation</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In-Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Workplan_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Workplan Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AIA_Workplan_Type__c.Used_For__c</field>
                <operation>equals</operation>
                <value>Implementation</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AIA_Workplan_Type__c</referenceTo>
        <relationshipLabel>Implementations</relationshipLabel>
        <relationshipName>Implementations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Implementation</label>
    <nameField>
        <displayFormat>IMP-{000000}</displayFormat>
        <label>Implementation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Implementations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Benfit_Request_Form__c.object
<CustomObject>
    <description>New object for AIA - This object stores the information that is needed for a quote</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Benefit Request Forms</relationshipLabel>
        <relationshipName>Benfit_Request_Forms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Benefit Request Forms</relationshipLabel>
        <relationshipName>Benfit_Request_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Benefit Request Form Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Benefit Request Form</label>
    <nameField>
        <displayFormat>BRF-{000000}</displayFormat>
        <label>Benefit Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Request Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Workplan_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Workplan Type</label>
        <referenceTo>AIA_Workplan_Type__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>AIA_200</fullName>
        <active>true</active>
        <businessProcess>AIA Large Group Sales Process</businessProcess>
        <description>200+ Opportunity Record Type</description>
        <label>200+</label>
    </recordTypes>
</CustomObject>

src/classes/AIA_ImplementationHandler.cls
//===================================================================================
//Date: 05/23/2016
//Developer: Sree Harsha Akkala
//=========================================================================================
// Update History
// Date         Developer               Description
//==================================================================================
// 05/23/2016    Sree Harsha Akkala      Initial Development
//==================================================================================

//public class AIA_Opportunity_ImplementationHandler
public class AIA_ImplementationHandler{
    
    public static boolean firstRun = false;

    public static Id RecType200Plus = QueryBase.getRecordTypeId('Opportunity', 'AIA_200');
    
    // TODO: What does this method do, add input and output parameters
    // TODO: Add comments
    // TODO: Only search for sold BRF
    // TODO: Only search for opportunity with a status of sold
    // TODO: Add error handling
    public static void createImplementation(list<opportunity> opportunityList){
        system.debug('@@ in createImplementation');
        list<Benfit_Request_Form__c> brfList = [select id,name,Status__c,Opportunity__c  from Benfit_Request_Form__c  where Opportunity__c in: opportunityList ];
        Map<id,id> oppBRFIdMap = new Map<id,id>();
        for(opportunity opp: opportunityList){
            for(Benfit_Request_Form__c brf:brfList){
                if(brf.Opportunity__c==opp.id){
                oppBRFIdMap.put(opp.id,brf.id);
                break;
                }   
            }
        }
        
        list<AIA_Implementation__c> PSIlist = new list<AIA_Implementation__c>();
        for(opportunity opp: opportunityList){
            if(opp.recordtypeId==RecType200Plus && opp.stageName=='Sold'){
                AIA_Implementation__c psi = new AIA_Implementation__c();
                psi.name__C =opp.name;
                psi.Description__c  =opp.description;
                psi.Workplan_Type__c = opp.Workplan_Type__c;
                psi.Status__c='Not Started';
                psi.Account__c = opp.accountId;
                psi.Benefit_Request_Form__c=oppBRFIdMap.get(opp.id);
                psi.Opportunity__c=opp.id;
                PSIlist.add(psi);
            }
        }
        firstRun =true;
        insert PSIlist;
        }
       
}