src/objects/Benfit_Request_Form__c.object
<CustomObject>
    <description>New object for AIA - This object stores the information that is needed for a quote</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Benefit Request Forms</relationshipLabel>
        <relationshipName>Benfit_Request_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Benefit Request Form Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Benefit Request Form</label>
    <nameField>
        <displayFormat>BRF-{000000}</displayFormat>
        <label>Benefit Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Request Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AIA_Opportunity_Helper.cls
/*------------------------------------------------------------------------------------
 *                      ----===[ HISTORY ]===---
 * Date        Developer        Description
 *------------------------------------------------------------------------------------
 * 05/19/2016 Chida--B-02108 
 B-02108 
 1.User can mark the Opportunity as sold (contract was awarded) if there is a Benefit Request Form marked as sold
                                 
 * 
  *************************************************************************************
 */
 
 //---------------------------------------------------------------------------------------------------------

/**
* @Author: Chida
* @Purpose: User can mark the Opportunity as sold (contract was awarded) if there is a Benefit Request Form marked as sold
    
* Input List of Opportunities
*/


public class AIA_Opportunity_Helper
{
    //List of Opportunities
    public void AIA_Opportunity_Helper(List<Opportunity> listOppty)
    {
      //  User can mark the Opportunity as sold (contract was awarded) if there is a Benefit Request Form marked as sold
    
        for(Opportunity opt: listOppty)
        {
         if(opt.StageName  == 'Sold')
        {
            List<Benfit_Request_Form__c> BRF=[select ID from Benfit_Request_Form__c where Status__c = 'Sold' AND Opportunity__c =: opt.id];
            if(BRF.size() < 1)
            {
                opt.adderror('There are no "Sold" Benefit Request Forms under it');
            }
        }
        }
    }
}