src/objects/Benfit_Request_Form__c.object
<CustomObject>
    <description>New object for AIA - This object stores the information that is needed for a quote</description>
    <fields>
        <fullName>Benefit_Effective_Date__c</fullName>
        <label>Benefit Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Benefit_Period__c</fullName>
        <label>Benefit Period</label>
        <picklist>
            <picklistValues>
                <fullName>Calendar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Broker_Commission__c</fullName>
        <defaultValue>(7/2)/100</defaultValue>
        <label>Broker Commission</label>
        <precision>18</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Contract_Count__c</fullName>
        <label>Contract Count</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contract_Period__c</fullName>
        <label>Contract Period</label>
        <picklist>
            <picklistValues>
                <fullName>Standard - 12 Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Standard</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Funding_Arrangements__c</fullName>
        <label>Funding Arrangements</label>
        <picklist>
            <picklistValues>
                <fullName>ASO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Both</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Grandfathered_Status__c</fullName>
        <label>Grandfathered Status</label>
        <picklist>
            <picklistValues>
                <fullName>Grandfathered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Grandfathered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mixed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <label>Jurisdiction</label>
        <picklist>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other - Cede Required</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MHP_Test_Result__c</fullName>
        <label>MHP Test Result</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request Type</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect/New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off-Cycle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFP</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Segment_Size__c</fullName>
        <label>Sales Segment Size</label>
        <picklist>
            <picklistValues>
                <fullName>Commercial 200-999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial 1,000+</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Labor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Municipal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Business</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Benefit Request Form</label>
    <nameField>
        <displayFormat>BRF-{000000}</displayFormat>
        <label>Benefit Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefit Request Forms</pluralLabel>
    <recordTypes>
        <fullName>ASO</fullName>
        <active>true</active>
        <description>ASO Layout</description>
        <label>ASO</label>
    </recordTypes>
    <recordTypes>
        <fullName>Both</fullName>
        <active>true</active>
        <description>Both Layout</description>
        <label>Both</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Proposed_Products__c.object
<CustomObject>
    <fields>
        <fullName>Benefit_Request_Form__c</fullName>
        <label>Benefit Request Form</label>
        <referenceTo>Benfit_Request_Form__c</referenceTo>
        <relationshipLabel>Proposed Products</relationshipLabel>
        <relationshipName>Proposed_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CDH__c</fullName>
        <label>CDH</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Deductible__c</fullName>
        <label>Deductible Options</label>
        <picklist>
            <picklistValues>
                <fullName>Stacked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Stacked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FSA_BlueFund__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FSA BlueFund</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Funding_Arrangement__c</fullName>
        <inlineHelpText>This field is prepopulated when the BRF funding arrangement is of type ASO/Risk</inlineHelpText>
        <label>Funding Arrangement</label>
        <picklist>
            <picklistValues>
                <fullName>ASO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Risk</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Grandfathered_Status__c</fullName>
        <label>Grandfathered Status</label>
        <picklist>
            <picklistValues>
                <fullName>Grandfathered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Grandfathered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Integrated_Non_Integrated__c</fullName>
        <label>RX Integration</label>
        <picklist>
            <picklistValues>
                <fullName>Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integrated - Carved-Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Integrated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MHP_Test_Result__c</fullName>
        <label>MHP Test Result</label>
        <picklist>
            <controllingField>Funding_Arrangement__c</controllingField>
            <picklistValues>
                <fullName>Pass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Proposed Products</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>Proposed Products Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposed Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AIA_PPHandler_Test.cls
//===================================================================================
//Date: 05/09/2016
//Developer: Sree Harsha Akkala
//Purpose: Test class for PPhandler.
//=========================================================================================
// Update History
// Date         Developer               Description
// 5/25/2016     PR                     Commented on line 44,35,37
//==================================================================================
//05/09/2016    Sree Harsha Akkala      Initial Development
//==================================================================================
@isTest
private class AIA_PPHandler_Test{
    static testmethod void testupdateMHPTest(){
            test.startTest();
            
            Benfit_Request_Form__c brf = new Benfit_Request_Form__c();
            brf.Request_Type__c='Prospect/New';
            brf.Benefit_Effective_Date__c   = system.today();
            brf.Benefit_Period__c='Calendar';
            brf.Jurisdiction__c ='VA';
            brf.Sales_Segment_Size__c = 'Labor';
            brf.Contract_Period__c = 'Standard 12 months';
            brf.Grandfathered_Status__c  = 'Grandfathered';
            brf.Broker_Commission__c = 3.5;
            brf.Contract_Count__c = 20;
            brf.Funding_Arrangements__c = 'Both';   
            
            insert brf;
            
            Proposed_Products__c pp = new Proposed_Products__c();
            pp.Benefit_Request_Form__c  = brf.id;
            pp.Integrated_Non_Integrated__c = 'Integrated';
            
           // pp.Blue_Rewards_Wellness__c = 'Yes';
            pp.Funding_Arrangement__c = 'ASO';
           // pp.FSA_BlueFund__c  = 'Yes';
            pp.Deductible__c = 'Stacked';
            pp.CDH__c = 'Yes';
            pp.MHP_Test_Result__c = 'Pass';
            insert pp;
                        
           // pp.Blue_Rewards_Wellness__c = 'No';
            update pp;  
            
            test.stopTest();
        
        
    }
}